spring:
  security:
    oauth2:
      client:
        provider:
          hyland-experience-auth:
            token-uri:

alfresco:
  bulk-ingester:
    endpoint: direct:test-bulk-ingester-endpoint
  transform:
    request:
      endpoint: direct:test-transform-request-endpoint
    response:
      queue-name: test-transform-reply-endpoint
      endpoint: direct:${alfresco.transform.response.queue-name}
    shared-file-store:
      retry:
        initial-delay: 0
    mime-type:
      mapping:
        '[image/png]': "image/png"
        '[image/bmp]': "image/png"
        '[image/gif]': "image/png"
        '[image/raw]': "image/png"
        '[image/tiff]': "image/png"
        '[image/*]': "image/jpeg"
        '[application/*]': "application/pdf"
        '[text/*]': "application/pdf"
hyland-experience:
  authentication:
    retry:
      initial-delay: 0
  storage:
    location:
      retry:
        initial-delay: 0
    upload:
      retry:
        initial-delay: 0
  ingester:
    retry:
      initial-delay: 0
    endpoint: direct:hxi-ingester-endpoint
