version: 2
registries:
  hylandsoftware-releases:
    type: maven-repository
    url: https://artifacts.alfresco.com/nexus/content/repositories/hylandsoftware-releases
    username: ${{secrets.NEXUS_USERNAME}}
    password: ${{secrets.NEXUS_PASSWORD}}
updates:
  - package-ecosystem: "maven"
    directory: "/"
    registries:
      - hylandsoftware-releases
    schedule:
      interval: "daily"
      time: "22:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 99
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: docker
    directory: "distribution/src/main/resources"
    schedule:
      interval: daily
      time: "22:00"
      timezone: Europe/London
    open-pull-requests-limit: 99
