server:
  port: ${SERVER_PORT:8657}

spring:
  reactor:
    netty:
      enabled: false

sync:
  enabled: ${SYNC_ENABLED:false}
  cron.expression: ${SYNC_CRON_EXPRESSION:0 0 0 * * *}

http-client:
  timeout-minutes: ${HTTP_CLIENT_TIMEOUT_MINUTES:5}
  buffer-size-kilobytes: ${HTTP_CLIENT_BUFFER_KB:10240}
  retry:
    max-attempts: ${HTTP_RETRY_MAX_ATTEMPTS:3}
    initial-delay-ms: ${HTTP_RETRY_INITIAL_DELAY_MS:2000}
    multiplier: ${HTTP_RETRY_MULTIPLIER:2}
    max-delay-ms: ${HTTP_RETRY_MAX_DELAY_MS:10000}

auth:
  providers:
    hyland-experience:
      type: ${AUTH_HX_TYPE:oauth2}
      client-id: ${HX_CLIENT_ID}
      client-secret: ${HX_CLIENT_SECRET}
      token-uri: ${HX_TOKEN_URI}
      grant-type: client_credentials
      scope:
        - iam.user-data.account
        - system-integrations-config
        - system-integrations-runtime
        - environment_authorization
      environment-key: ${AUTH_PROVIDERS_HYLANDEXPERIENCE_ENVIRONMENTKEY}
      client-name: acs-insight-connector

alfresco:
  base-url: ${ALFRESCO_BASE_URL}
  page-size: 100
  user:
    skip-not-enabled: ${ALFRESCO_SKIP_DISABLED_USER:true}
  user-group:
    fetch-timeout: ${ALFRESCO_USR_GRP_FETCH_TIMEOUT:PT5M}
    max-concurrent-requests: ${ALFRESCO_USR_GRP_MAX_REQUESTS:5}

nucleus:
  idp-base-url: ${NUCLEUS_IDP_BASE_URL}
  base-url: ${NUCLEUS_BASE_URL}
  system-id: ${NUCLEUS_SYSTEM_ID}
  page-size: 1000
  sync-batch-size: 1000
  delete-group-member-batch-size: ${DELETE_BATCH_SIZE:100}

logging:
  level:
    org.alfresco.hxi_connector: ${LOGGING_LEVEL_ORG_ALFRESCO:INFO}
    org.springframework.web.reactive.function.client: DEBUG
