services:
  alfresco:
    extends:
      file: docker-compose.yml
      service: alfresco
    environment:
      JAVA_OPTS: "
        -Ddb.driver=org.postgresql.Driver
        -Ddb.username=alfresco
        -Ddb.password=alfresco
        -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
        -Dalfresco.host=localhost
        -Dalfresco.port=8080
        -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
        -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
        -Ddeployment.method=DOCKER_COMPOSE
        -Dtransform.service.enabled=true
        -Dtransform.service.url=http://transform-router:8095
        -Dsfs.url=http://shared-file-store:8099/
        -DlocalTransform.core-aio.url=http://transform-core-aio:8090/
        -Dalfresco-pdf-renderer.url=http://transform-core-aio:8090/
        -Djodconverter.url=http://transform-core-aio:8090/
        -Dimg.url=http://transform-core-aio:8090/
        -Dtika.url=http://transform-core-aio:8090/
        -Dtransform.misc.url=http://transform-core-aio:8090/
        -Dcsrf.filter.enabled=false
        -Dalfresco.restApi.basicAuthScheme=true
        -Xms1500m -Xmx1500m
        -Dhxi.client.base-url=http://hxinsight-mock:8080
        -Dhxi.auth.providers.hyland-experience.token-uri=http://hxinsight-mock:8080/token
        "
    ports:
      - "8080:8080"

  postgres:
    extends:
      file: docker-compose.yml
      service: postgres

  activemq:
    extends:
      file: docker-compose.yml
      service: activemq

  transform-router:
    extends:
      file: docker-compose.yml
      service: transform-router

  transform-core-aio:
    extends:
      file: docker-compose.yml
      service: transform-core-aio

  shared-file-store:
    extends:
      file: docker-compose.yml
      service: shared-file-store

  live-ingester:
    extends:
      file: docker-compose.yml
      service: live-ingester

  hxinsight-mock:
    extends:
      file: docker-compose.yml
      service: hxinsight-mock

  aws-mock:
    extends:
      file: docker-compose.yml
      service: aws-mock

volumes:
  shared-file-store-volume:
    driver_opts:
      type: tmpfs
      device: tmpfs
