version: "3.8"

services:
  alfresco:
    image: quay.io/alfresco/alfresco-content-repository:${ALFRESCO_TAG}
    deploy:
      resources:
        limits:
          memory: 1700m
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n"
      JAVA_TOOL_OPTIONS: "
        -Dencryption.keystore.type=JCEKS
        -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
        -Dencryption.keyAlgorithm=DESede
        -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
        -Dmetadata-keystore.password=mp6yc0UD9e
        -Dmetadata-keystore.aliases=metadata
        -Dmetadata-keystore.metadata.password=oKIWzVdEdA
        -Dmetadata-keystore.metadata.algorithm=DESede
        "
      JAVA_OPTS: "
        -Delasticsearch.createIndexIfNotExists=true
        -Ddb.driver=org.postgresql.Driver
        -Ddb.username=alfresco
        -Ddb.password=alfresco
        -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
        -Dindex.subsystem.name=elasticsearch
        -Delasticsearch.host=elasticsearch
        -Delasticsearch.indexName=alfresco
        -Dshare.host=localhost
        -Dshare.port=8080
        -Dalfresco.host=localhost
        -Dalfresco.port=8080
        -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
        -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
        -Ddeployment.method=DOCKER_COMPOSE
        -Dtransform.service.enabled=true
        -Dtransform.service.url=http://transform-router:8095
        -Dsfs.url=http://shared-file-store:8099/
        -DlocalTransform.core-aio.url=http://transform-core-aio:8090/
        -Dalfresco-pdf-renderer.url=http://transform-core-aio:8090/
        -Djodconverter.url=http://transform-core-aio:8090/
        -Dimg.url=http://transform-core-aio:8090/
        -Dtika.url=http://transform-core-aio:8090/
        -Dtransform.misc.url=http://transform-core-aio:8090/
        -Dcsrf.filter.enabled=false
        -Dalfresco.restApi.basicAuthScheme=true
        -Xms1500m -Xmx1500m
        "
    ports:
      - "8000:8000"
    healthcheck:
      test: curl --fail http://localhost:8080/alfresco || exit 1
      start_period: 90s
      interval: 10s
      timeout: 3s
      retries: 20

  postgres:
    image: postgres:${POSTGRES_TAG}
    deploy:
      resources:
        limits:
          memory: 512m
    environment:
      POSTGRES_PASSWORD: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_DB: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "5432:5432"

  activemq:
    image: quay.io/alfresco/alfresco-activemq:${ACTIVE_MQ_TAG}
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
      - "8161:8161" # Web Console
      - "5672:5672" # AMQP
      - "61616:61616" # OpenWire
      - "61613:61613" # STOMP

  transform-router:
    image: quay.io/alfresco/alfresco-transform-router:${TRANSFORM_ROUTER_TAG}
    deploy:
      resources:
        limits:
          memory: 512m
    environment:
      JAVA_OPTS: " -Xms256m -Xmx512m"
      ACTIVEMQ_URL: "nio://activemq:61616"
      CORE_AIO_URL: "http://transform-core-aio:8090"
      FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
    ports:
      - "8095:8095"
    links:
      - activemq

  transform-core-aio:
    image: quay.io/alfresco/alfresco-transform-core-aio:${TRANSFORM_CORE_AIO_TAG}
    deploy:
      resources:
        limits:
          memory: 1536m
    environment:
      JAVA_OPTS: " -Xms256m -Xmx1536m"
      ACTIVEMQ_URL: "nio://activemq:61616"
      FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
    ports:
      - "8090:8090"
    links:
      - activemq

  shared-file-store:
    image: quay.io/alfresco/alfresco-shared-file-store:${SHARED_FILE_STORE_TAG}
    deploy:
      resources:
        limits:
          memory: 512m
    environment:
      JAVA_OPTS: " -Xms256m -Xmx512m"
      scheduler.content.age.millis: 86400000
      scheduler.cleanup.interval: 86400000
    ports:
      - "8099:8099"
    volumes:
      - shared-file-store-volume:/tmp/Alfresco/sfs

  share:
    image: quay.io/alfresco/alfresco-share:${SHARE_TAG}
    deploy:
      resources:
        limits:
          memory: 512m
    environment:
      REPO_HOST: "alfresco"
      REPO_PORT: "8080"
      JAVA_OPTS: "
        -Dalfresco.host=localhost
        -Dalfresco.port=8080
        -Dalfresco.context=alfresco
        -Dalfresco.protocol=http
        -Xms512m -Xmx512m
        "

  digital-workspace:
    image: quay.io/alfresco/alfresco-digital-workspace:${DIGITAL_WORKSPACE_TAG}
    deploy:
      resources:
        limits:
          memory: 128m
    environment:
      APP_CONFIG_PROVIDER: "ECM"
      APP_CONFIG_AUTH_TYPE: "BASIC"
      BASE_PATH: ./
      APP_BASE_SHARE_URL: "http://localhost:8080/workspace/#/preview/s"

  control-center:
    image: quay.io/alfresco/alfresco-control-center:${CONTROL_CENTER_TAG}
    deploy:
      resources:
        limits:
          memory: 128m
    environment:
      APP_CONFIG_PROVIDER: "ECM"
      APP_CONFIG_AUTH_TYPE: "BASIC"
      BASE_PATH: ./

  # HTTP proxy to provide HTTP Default port access to services
  proxy:
    image: alfresco/alfresco-acs-nginx:${ACS_NGINX_TAG}
    deploy:
      resources:
        limits:
          memory: 128m
    environment:
      DISABLE_SYNCSERVICE: "true"
    depends_on:
      - alfresco
      - digital-workspace
      - control-center
    ports:
      - "8080:8080"
    links:
      - digital-workspace
      - alfresco
      - share
      - control-center

  elasticsearch:
    image: elasticsearch:${ELASTICSEARCH_TAG}
    deploy:
      resources:
        limits:
          memory: 1700m
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    #    volumes:
    #      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  reindexing:
    image: quay.io/alfresco/alfresco-elasticsearch-reindexing:${SEARCH_ENTERPRISE_TAG}
    deploy:
      resources:
        limits:
          memory: 512m
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,address=*:5006,server=y,suspend=n
      SPRING_ELASTICSEARCH_REST_URIS: http://elasticsearch:9200
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/alfresco
      SPRING_ACTIVEMQ_BROKER-URL: nio://activemq:61616
      ALFRESCO_REINDEX_BATCH_SIZE: 100
      ALFRESCO_REINDEX_CONCURRENT_PROCESSORS: 4
      ALFRESCO_REINDEX_FROM_ID: 0
      ALFRESCO_REINDEX_TO_ID: 1000
      ALFRESCO_REINDEX_JOB_NAME: reindexByIds
      ELASTICSEARCH_INDEX_NAME: alfresco
      ALFRESCO_REINDEX_PATHINDEXINGENABLED: true
      ALFRESCO_ACCEPTEDCONTENTMEDIATYPESCACHE_BASEURL: http://transform-core-aio:8090/transform/config
    ports:
      - "5006:5006"
    depends_on:
      elasticsearch:
        condition: service_started
      alfresco:
        condition: service_healthy

  live-indexing:
    image: quay.io/alfresco/alfresco-elasticsearch-live-indexing:${SEARCH_ENTERPRISE_TAG}
    deploy:
      resources:
        limits:
          memory: 512m
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n
      ELASTICSEARCH_INDEXNAME: alfresco
      SPRING_ELASTICSEARCH_REST_URIS: http://elasticsearch:9200
      SPRING_ACTIVEMQ_BROKERURL: nio://activemq:61616
      ALFRESCO_SHAREDFILESTORE_BASEURL: http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file/
      ALFRESCO_ACCEPTEDCONTENTMEDIATYPESCACHE_BASEURL: http://transform-core-aio:8090/transform/config
    ports:
      - "5005:5005"
    depends_on:
      reindexing:
        condition: service_completed_successfully

  live-ingester:
    image: quay.io/alfresco/alfresco-hxinsight-connector-live-ingester:${HXINSIGHT_CONNECTOR_TAG}
    deploy:
      resources:
        limits:
          memory: 512m
    depends_on:
      - activemq
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,address=*:5007,server=y,suspend=n
      LOGGING_LEVEL_ORG_ALFRESCO: DEBUG
      SPRING_ACTIVEMQ_BROKERURL: nio://activemq:61616
      HYLAND_EXPERIENCE_INSIGHT_API_URL_INGEST: http://hxinsight-mock:8080/ingest
      HYLAND_EXPERIENCE_INSIGHT_API_URL_STORAGE-LOCATION-REQUEST: http://hxinsight-mock:8080/pre-signed-url
      ALFRESCO_TRANSFORM_SHARED-FILE-STORE_HOST: http://shared-file-store
      ALFRESCO_TRANSFORM_SHARED-FILE-STORE_PORT: 8099
    ports:
      - "5007:5007"

  hxinsight-mock:
    image: wiremock/wiremock:${WIREMOCK_TAG}
    deploy:
      resources:
        limits:
          memory: 256m
    command: "--global-response-templating --permitted-system-keys=AWS_.* --verbose"
    environment:
      AWS_HOST: aws-mock
      AWS_PORT: 4566
      AWS_S3_BUCKET_NAME: hxinsight-bucket-mock
    volumes:
      - ./wiremock/hxinsight:/home/wiremock

  aws-mock:
    image: localstack/localstack:${LOCALSTACK_TAG}
    deploy:
      resources:
        limits:
          memory: 256m
    environment:
      SERVICES: s3
      BUCKET_NAME: hxinsight-bucket-mock
    ports:
      - "4566:4566"
    volumes:
      - './init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh'

volumes:
  shared-file-store-volume:
    driver_opts:
      type: tmpfs
      device: tmpfs
