server:
  port: 8080

management:
  endpoints.web.exposure.include: health
  endpoint.health.probes.enabled: true
  health.liveness-state.enabled: true
  health.readiness-state.enabled: true

camel:
  springboot.main-run-controller: true
  dataformat.jackson.autoDiscoverObjectMapper: true

application:
  source-id: alfresco-dummy-source-id-0a63de491876
  version: "@project.version@"

logging.pattern.console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %replace(%msg){'\"?Authorization\"?=\"?[a-zA-Z0-9-_.\" \"]*\"?+', 'Authorization=*****'}%n"

alfresco:
  repository:
    events-endpoint: activemq:topic:alfresco.repo.event2
    base-url: http://localhost:8080/alfresco
    discovery-endpoint: ${alfresco.repository.base-url}/api/discovery
    health-probe:
      endpoint: ${alfresco.repository.base-url}
      timeout-seconds: 1800
      interval-seconds: 30
  bulk-ingester:
    endpoint: activemq:queue:bulk-ingester-events
  transform:
    request:
      endpoint: activemq:queue:acs-repo-transform-request?jmsMessageType=Text
      timeout: 20000
      options:
        "[image/png]":
          resizeWidth: 3840
          resizeHeight: 3840
          allowEnlargement: false
        "[image/jpeg]":
          resizeWidth: 3840
          resizeHeight: 3840
          allowEnlargement: false
    response:
      queue-name: org.alfresco.hxinsight-connector.transform.response
      endpoint: activemq:queue:${alfresco.transform.response.queue-name}
      retry-ingestion:
        attempts: -1
    shared-file-store:
      base-url: http://localhost:8099
      file-endpoint: ${alfresco.transform.shared-file-store.base-url}/alfresco/api/-default-/private/sfs/versions/1/file
  filter:
    aspect:
      allow:
      deny:
    type:
      allow:
      deny:
    path:
      allow:
      deny:
hyland-experience:
  insight:
    ingestion:
      base-url: http://localhost:8001
  storage:
    location:
      endpoint: ${hyland-experience.insight.ingestion.base-url}/presigned-urls?httpMethod=POST&throwExceptionOnFailure=false
  ingester:
    endpoint: ${hyland-experience.insight.ingestion.base-url}/ingestion-events?httpMethod=POST&throwExceptionOnFailure=false

auth:
  providers:
    hyland-experience:
      type: oauth2
      client-id:
      client-secret:
      token-uri: http://localhost:8001/token
      grant-type: client_credentials
      scope:
        - hxp.integrations
      environment-key: hxi-env-key
      client-name: acs-insight-connector
    alfresco:
      type: basic
      username:
      password:
  retry:
    attempts: 10
    initial-delay: 500
    delay-multiplier: 2
