spring:
  main:
    web-application-type: none

camel:
  springboot.main-run-controller: true
  dataformat.jackson.autoDiscoverObjectMapper: true

alfresco:
  repository:
    endpoint: activemq:topic:alfresco.repo.event2
  bulk-ingester:
    endpoint: activemq:queue:bulk-ingester-events
  transform:
    request:
      endpoint: activemq:queue:acs-repo-transform-request?jmsMessageType=Text
      timeout: 20000
      options:
        "[image/png]":
          resizeWidth: 3840
          resizeHeight: 3840
          allowEnlargement: false
        "[image/jpeg]":
          resizeWidth: 3840
          resizeHeight: 3840
          allowEnlargement: false
    response:
      queue-name: org.alfresco.hxinsight-connector.transform.response
      endpoint: activemq:queue:${alfresco.transform.response.queue-name}
      retry-ingestion:
        attempts: -1
    shared-file-store:
      host: http://localhost
      port: 8099
  filter:
    aspect:
      allow:
      deny:
    type:
      allow:
      deny:
    path:
      allow:
      deny:
hyland-experience:
  insight:
    base-url: http://localhost:8001
  authentication:
    refresh-delay-minutes: 55
  authorization:
    application-name: acs-insight-connector
    service-user: insight-acs
    environment-key:
  storage:
    location:
      endpoint: ${hyland-experience.insight.base-url}/presigned-urls?httpMethod=POST&throwExceptionOnFailure=false
  ingester:
    endpoint: ${hyland-experience.insight.base-url}/ingestion-events?httpMethod=POST&throwExceptionOnFailure=false

auth:
  providers:
    hyland-experience:
      type: oauth2
      client-id:
      client-secret:
      token-uri: http://localhost:8001/token
      grant-type: urn:hyland:params:oauth:grant-type:api-credentials
      scope: hxp.integrations
    alfresco:
      type: basic
      username:
      password:
  retry:
    attempts: 10
    initial-delay: 500
    delay-multiplier: 2
