camel:
  springboot.main-run-controller: true
  dataformat.jackson.autoDiscoverObjectMapper: true

alfresco:
  ingester:
    messaging:
        in.endpoint: activemq:topic:alfresco.repo.event2
        out.endpoint: http:localhost:8001/ingest?httpMethod=POST
  transform:
    messaging:
      request:
        endpoint: activemq:queue:acs-repo-transform-request?jmsMessageType=Text
        timeout: 20000
      response.queueName: org.alfresco.hxinsight-connector.transform.response
