camel:
  springboot.main-run-controller: true
  dataformat.jackson.autoDiscoverObjectMapper: true

hyland:
  experience:
    insight:
      api:
        username: dummy_user
        password: dummy_pass
        url:
          storage-location-request: http://localhost:8001/pre-signed-url
          ingest: http://localhost:8001/ingest

alfresco:
  integration:
    repository:
      endpoint: activemq:topic:alfresco.repo.event2
    transform:
      request:
        endpoint: activemq:queue:acs-repo-transform-request?jmsMessageType=Text
        timeout: 20000
      response:
        endpoint: activemq:queue:${alfresco.transform.response.queueName}
        queueName: org.alfresco.hxinsight-connector.transform.response
      shared-file-store:
        host: http://localhost
        port: 8099
    storage:
      location:
        endpoint: "${hyland.experience.insight.api.url.storage-location-request}\
          ?httpMethod=POST\
          &authMethod=Basic\
          &authUsername=${hyland.experience.insight.api.username}\
          &authPassword=${hyland.experience.insight.api.password}\
          &authenticationPreemptive=true\
          &throwExceptionOnFailure=false"
    ingester:
      endpoint: ${hyland.experience.insight.api.url.ingest}?httpMethod=POST
