server:
  port: 8077

logging:
  level:
    org.alfresco: ${LOGGING_LEVEL_ORG_ALFRESCO:DEBUG}

spring:
  activemq:
    broker-url: ${SPRING_ACTIVEMQ_BROKERURL:tcp://localhost:61616}
    packages:
      trust-all: true

management:
  endpoints.web.exposure.include: health
  endpoint.health.probes.enabled: true
  health.liveness-state.enabled: true
  health.readiness-state.enabled: true

camel:
  springboot.main-run-controller: true
  dataformat.jackson.autoDiscoverObjectMapper: true
  main.auto-startup: false

application:
  source-id: ${APPLICATION_SOURCEID}
  version: "@project.version@"

alfresco:
  repository:
    events-endpoint: activemq:topic:alfresco.repo.event2
    base-url: ${ALFRESCO_REPOSITORY_BASEURL:http://localhost:8080/alfresco}
    discovery-endpoint: ${alfresco.repository.base-url}/api/discovery
    health-probe:
      endpoint: ${alfresco.repository.base-url}
      timeout-seconds: 1800
      interval-seconds: 30
  bulk-ingester:
    endpoint: activemq:queue:bulk-ingester-events
  transform:
    request:
      endpoint: activemq:queue:acs-repo-transform-request?jmsMessageType=Text
      timeout: 20000
      options:
        "[image/png]":
          resizeWidth: 3840
          resizeHeight: 3840
          allowEnlargement: false
        "[image/jpeg]":
          resizeWidth: 3840
          resizeHeight: 3840
          allowEnlargement: false
    response:
      queue-name: org.alfresco.hxinsight-connector.transform.response
      endpoint: activemq:queue:${alfresco.transform.response.queue-name}
      retry-ingestion:
        attempts: -1
    shared-file-store:
      base-url: ${ALFRESCO_TRANSFORM_SHAREDFILESTORE_BASEURL:http://localhost:8099}
      file-endpoint: ${alfresco.transform.shared-file-store.base-url}/alfresco/api/-default-/private/sfs/versions/1/file
  filter:
    aspect:
      allow:
      deny:
    type:
      allow:
      deny:
    path:
      allow:
      deny:
    identity:
      allow: cm:person, cm:authorityContainer, usr:user
      deny:


hyland-experience:
  insight:
    ingestion:
      base-url: ${HYLANDEXPERIENCE_INSIGHT_INGESTION_BASEURL:https://ingestion.insight.dev.experience.hyland.com/v1}
  storage:
    digest-algorithm: SHA-256
    location:
      endpoint: ${hyland-experience.insight.ingestion.base-url}/presigned-urls?httpMethod=POST&throwExceptionOnFailure=false
  ingester:
    endpoint: ${hyland-experience.insight.ingestion.base-url}/ingestion-events?httpMethod=POST&throwExceptionOnFailure=false
nucleus:
  idp-base-url: ${NUCLEUS_IDP_BASE_URL:https://auth.iam.dev.experience.hyland.com}
  base-url: ${NUCLEUS_BASE_URL:https://api.nucleus.dev.experience.hyland.com}
  system-id: ${NUCLEUS_SYSTEM_ID:aaca2d59-e43f-47dc-a089-852245390852}
  page-size: 1000
  sync-batch-size: 1000
  delete-group-member-batch-size: ${DELETE_BATCH_SIZE:100}

authentication:
  providers:
    hyland-experience:
      type: oauth2
      client-id: ${AUTH_PROVIDERS_HYLANDEXPERIENCE_CLIENTID}
      client-secret: ${AUTH_PROVIDERS_HYLANDEXPERIENCE_CLIENTSECRET}
      token-uri: ${AUTH_PROVIDERS_HYLANDEXPERIENCE_TOKENURI}
      grant-type: ${AUTH_PROVIDERS_HYLANDEXPERIENCE_GRANTTYPE:client_credentials}
      scope:
        - iam.user-data.account
        - system-integrations-config
        - system-integrations-runtime
        - environment_authorization
        - iam.scim
      environment-key: ${AUTH_PROVIDERS_HYLANDEXPERIENCE_ENVIRONMENTKEY}
      client-name: acs-insight-connector
    alfresco:
      type: basic
      username: ${AUTH_PROVIDERS_ALFRESCO_USERNAME:admin}
      password: ${AUTH_PROVIDERS_ALFRESCO_PASSWORD:admin}
  retry:
    attempts: 10
    initial-delay: 500
    delay-multiplier: 2
