spring:
  main:
    web-application-type: none
  security:
    oauth2:
      client:
        registration:
          hyland-experience-auth:
            authorization-grant-type: urn:hyland:params:oauth:grant-type:api-credentials
            client-id: dummy-client-id
            client-secret: dummy-client-pass
            client-name: ${hyland-experience.authorization.application-name}
            scope: hxp.integrations
        provider:
          hyland-experience-auth:
            token-uri:

camel:
  springboot.main-run-controller: true
  dataformat.jackson.autoDiscoverObjectMapper: true

alfresco:
  repository:
    endpoint: activemq:topic:alfresco.repo.event2
  bulk-ingester:
    endpoint: activemq:queue:bulk-ingester-events
  transform:
    request:
      endpoint: activemq:queue:acs-repo-transform-request?jmsMessageType=Text
      timeout: 20000
    response:
      queue-name: org.alfresco.hxinsight-connector.transform.response
      endpoint: activemq:queue:${alfresco.transform.response.queue-name}
    shared-file-store:
      host: http://localhost
      port: 8099
hyland-experience:
  insight:
    base-url: http://localhost:8001
  authentication:
    refresh-delay-minutes: 55
  authorization:
    application-name: acs-insight-connector
    service-user: insight-acs
    environment-key: hxai-env-key
  storage:
    location:
      endpoint: ${hyland-experience.insight.base-url}/pre-signed-url?httpMethod=POST&throwExceptionOnFailure=false
  ingester:
    endpoint: ${hyland-experience.insight.base-url}/ingest?httpMethod=POST&throwExceptionOnFailure=false
