camel:
  springboot.main-run-controller: true
  dataformat.jackson.autoDiscoverObjectMapper: true

hyland:
  experience:
    insight:
      api:
        username: dummy_user
        password: dummy_pass
        url:
          storage-location-request: http://localhost:8001/pre-signed-url
          ingest: http://localhost:8001/ingest

alfresco:
  integration:
    storage:
      endpoint: "${hyland.experience.insight.api.url.storage-location-request}\
        ?httpMethod=POST\
        &authMethod=Basic\
        &authUsername=${hyland.experience.insight.api.username}\
        &authPassword=${hyland.experience.insight.api.password}\
        &authenticationPreemptive=true\
        &throwExceptionOnFailure=false"
      retry:
        attempts: 10
        initialDelay: 1000
        deleyMultiplier: 2
        reasons:
          - org.alfresco.hxi_connector.live_ingester.domain.exception.EndpointServerErrorException
          - java.net.UnknownHostException
          - java.net.MalformedURLException
          - com.fasterxml.jackson.core.io.JsonEOFException
          - com.fasterxml.jackson.databind.exc.MismatchedInputException
          - org.apache.hc.client5.http.HttpHostConnectException
          - org.apache.hc.core5.http.MalformedChunkCodingException
          - org.apache.hc.core5.http.NoHttpResponseException
  ingester:
    messaging:
      in.endpoint: activemq:topic:alfresco.repo.event2
      out.endpoint: ${hyland.experience.insight.api.url.ingest}?httpMethod=POST
  transform:
    request:
      endpoint: activemq:queue:acs-repo-transform-request?jmsMessageType=Text
      timeout: 20000
    response:
      queueName: org.alfresco.hxinsight-connector.transform.response
      endpoint: activemq:queue:${alfresco.transform.response.queueName}
    shared-file-store:
      host: http://localhost
      port: 8099
