camel:
  springboot:
    main-run-controller: true
  component:
    aws2-sqs:
      override-endpoint: true
      uri-endpoint-override: http://localhost:4566
      access-key: dummy_access_key
      secret-key: dummy_secret_key

hyland-experience:
  insight:
    prediction:
      endpoint: aws2-sqs://arn:aws:sqs:us-east-1:000000000000:hxinsight-prediction-queue
    prediction-listener:
      predictions-endpoint: http:localhost:8080/predictions?pageSize=10
      prediction-processor-trigger-endpoint: quartz:prediction-processor-trigger?cron=0+*/1+*+?+*+*

alfresco:
  repository:
    nodes:
      base-url: http://localhost:8080
      username:
      password:
      retry:
        attempts: 10
        initial-delay: 500
        delay-multiplier: 2
