server:
  port: 8080

management:
  endpoints.web.exposure.include: health
  endpoint.health.probes.enabled: true
  health.liveness-state.enabled: true
  health.readiness-state.enabled: true

camel:
  springboot:
    main-run-controller: true
  main:
    auto-startup: false

application:
  source-id: a1f3e7c0-d193-7023-ce1d-0a63de491876
  version: "@project.version@"

hyland-experience:
  insight:
    predictions:
      base-url: http://localhost:8001
      poll-period-millis: 300_000 # 5 minutes

alfresco:
  repository:
    base-url: http://localhost:8002/alfresco
    discovery-endpoint: ${alfresco.repository.base-url}/api/discovery
    retry:
      attempts: 10
      initial-delay: 500
      delay-multiplier: 2
    health-probe:
      endpoint: ${alfresco.repository.base-url}
      timeout-seconds: 1800
      interval-seconds: 30
auth:
  providers:
    hyland-experience:
      type: oauth2
      client-id:
      client-secret:
      token-uri: http://localhost:8001/token
      grant-type: client_credentials
      scope:
        - hxp.integrations
      environment-key: hxi-env-key
      client-name: acs-insight-connector
    alfresco:
      type: basic
      client-id:
      username:
      password:
  retry:
    attempts: 10
    initial-delay: 500
    delay-multiplier: 2
