camel:
  springboot:
    main-run-controller: true
  component:
    aws2-sqs:
      override-endpoint: true
      uri-endpoint-override: http://localhost:4566
      access-key: dummy_access_key
      secret-key: dummy_secret_key

hyland-experience:
  insight:
    prediction:
      endpoint: direct:test
    prediction-listener:
      poll-period: 300_000 #5 min
      predictions-source-endpoint: direct:mocked
      internal-predictions-buffer-endpoint: activemq:queue:predictions-buffer

alfresco:
  repository:
    nodes:
      base-url: http://localhost:8080
      username:
      password:
      retry:
        attempts: 10
        initial-delay: 500
        delay-multiplier: 2
