spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:postgresql://localhost:5432/alfresco
    username: alfresco
    password: alfresco

camel:
  springboot:
    main-run-controller: true

hyland-experience:
  insight:
    predictions:
      source-base-url: http://localhost:8001
      poll-period-millis: 300_000 # 5 minutes

alfresco:
  repository:
    base-url: http://localhost:8002
    retry:
      attempts: 10
      initial-delay: 500
      delay-multiplier: 2

auth:
  providers:
    hyland-experience:
      type: oauth2
      client-id:
      client-secret:
      token-uri: http://localhost:8001/token
      grant-type: urn:hyland:params:oauth:grant-type:api-credentials
      scope:
       - hxp.integrations
      environment-key: hxi-env-key
      client-name: acs-insight-connector
    alfresco:
      type: basic
      client-id: dummy-client-id
      username: alfresco
      password: alfresco
  retry:
    attempts: 10
    initial-delay: 500
    delay-multiplier: 2
