server:
  port: 8080

management:
  endpoints.web.exposure.include: health
  endpoint.health.probes.enabled: true
  health.liveness-state.enabled: true
  health.readiness-state.enabled: true

camel:
  springboot:
    main-run-controller: true

application:
  source-id: alfresco-dummy-source-id-0a63de491876
  version: "@project.version@"

hyland-experience:
  insight:
    predictions:
      base-url: http://localhost:8001
      poll-period-millis: 300_000 # 5 minutes

alfresco:
  repository:
    base-url: http://localhost:8002
    discovery-endpoint: ${alfresco.repository.base-url}/alfresco/api/discovery
    retry:
      attempts: 10
      initial-delay: 500
      delay-multiplier: 2

auth:
  providers:
    hyland-experience:
      type: oauth2
      client-id:
      client-secret:
      token-uri: http://localhost:8001/token
      grant-type: client_credentials
      scope:
       - hxp.integrations
      environment-key: hxi-env-key
      client-name: acs-insight-connector
    alfresco:
      type: basic
      client-id:
      username:
      password:
  retry:
    attempts: 10
    initial-delay: 500
    delay-multiplier: 2
