spring:
  main:
    web-application-type: none
  security:
    oauth2:
      client:
        registration:
          hyland-experience-auth:
            authorization-grant-type: urn:hyland:params:oauth:grant-type:api-credentials
            client-id: dummy-client-id
            client-secret: dummy-client-pass
            client-name: ${hyland-experience.authorization.application-name}
            scope: hxp.integrations
        provider:
          hyland-experience-auth:
            token-uri: http://localhost:8001/token

camel:
  springboot:
    main-run-controller: true

hyland-experience:
  authentication:
    refresh-delay-minutes: 55
  authorization:
    application-name: acs-insight-connector
    service-user: insight-acs
    environment-key: hxai-env-key
  insight:
    predictions:
      source-endpoint: http://localhost:8080/prediction-batches
      buffer-endpoint: activemq:queue:predictions-buffer
      poll-period-millis: 300_000 # 5 minutes

alfresco:
  repository:
    nodes:
      base-url: http://localhost:8080
      username:
      password:
      retry:
        attempts: 10
        initial-delay: 500
        delay-multiplier: 2
