name: TCK Test Run
description: "Run TCK tests"
inputs:
  hyland-tck-pat:
    description: PAT for accessing TCK
    required: true
  maven-cli-opts:
    description: Maven options string
    default: ''
  github-token:
    description: GitHub token for GHCR login
    required: true
runs:
  using: "composite"
  steps:
    - uses: Alfresco/alfresco-build-tools/.github/actions/free-hosted-runner-disk-space@v8.14.1
    - name: "Clone TCK repository"
      shell: bash
      run: ./scripts/ci/cloneTCK.sh
      env:
        GITHUB_TOKEN: ${{ inputs.hyland-tck-pat }}
    - name: GHCR Login
      uses: docker/login-action@v3.4.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}
    - name: Docker Compose Up
      shell: bash
      run: |
        cd ${{ env.tck }}
        docker compose up -d
    - name: "Set up JDK"
      uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v8.14.1
    - name: "Build application"
      shell: bash
      run: mvn ${{ inputs.maven-cli-opts }} clean install -DskipTests -pl live-ingester -am
    - name: "Run OpenApi Specification tests"
      shell: bash
      run: mvn test -Dtest=OpenApiTckRequestValidationTest -pl live-ingester
    - name: "Output TCK logs"
      if: success() || failure()
      shell: bash
      run: docker logs ingestion-connector-tck-api-1
    - name: Docker Compose Down
      shell: bash
      run: |
        cd ${{ env.tck }}
        docker compose down
