name: Alfresco Connector for Hyland Experience Insight CI

on:
  pull_request:
    branches:
      - feature/**
      - fix/**
      - master
      - release/**
  push:
    branches:
      - feature/**
      - fix/**
      - master
      - release/**

env:
  # Both variables are required to be set before the release process starts .
  # As the release is triggered by a commit message with "[release]" keyword on a release branch,
  # setting these variables to new values can be done in the same commit and will indicate the release and the dev versions in it.
  DEVELOPMENT_VERSION: "1.0.0-SNAPSHOT" # The version that will be set in pom files after the release (next dev version)
  RELEASE_VERSION: "1.0.0-A6" # The version of the release (tag).
  GITHUB_ACTIONS_DEPLOY_TIMEOUT: 60
  MAVEN_CLI_OPTS: "-B -e -fae -V -DinstallAtEnd=true -DfailIfNoTests=false -U -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Pdistribution "
  MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  JAVA_VERSION: "17"
  S3_BUCKET_REGION: "eu-west-1"

jobs:
  pmd_scan:
    name: "PMD Scan"
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'pull_request' &&
      !contains(github.event.head_commit.message, '[skip pmd]') &&
      !contains(github.event.head_commit.message, '[skip tests]')
    steps:
      - uses: actions/checkout@v4
      - uses: Alfresco/alfresco-build-tools/.github/actions/free-hosted-runner-disk-space@v5.33.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v5.33.0
      - uses: Alfresco/ya-pmd-scan@de9c4d578f1f05cc16af56fb1df8246a86c56436
