name: Alfresco Connector for Hyland Experience Insight CI

on:
  pull_request:
    branches:
      - feature/**
      - fix/**
      - master
      - release/**
  push:
    branches:
      - feature/**
      - fix/**
      - master
      - release/**

env:
  # Both variables are required to be set before the release process starts .
  # As the release is triggered by a commit message with "[release]" keyword on a release branch,
  # setting these variables to new values can be done in the same commit and will indicate the release and the dev versions in it.
  DEVELOPMENT_VERSION: "2.0.1-SNAPSHOT" # The version that will be set in pom files after the release (next dev version)
  RELEASE_VERSION: "2.0.0-A.4" # The version of the release (tag).
  GITHUB_ACTIONS_DEPLOY_TIMEOUT: 60
  MAVEN_CLI_OPTS: "-B -e -fae -V -DinstallAtEnd=true -DfailIfNoTests=false -U -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Pdistribution "
  MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  JAVA_VERSION: "17"
  JAVA_VERSION_SUPPORTED_BY_REPO: "11"
  S3_BUCKET_REGION: "eu-west-1"

jobs:
  tck_tests:
    name: "Run TCK tests before release"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Run TCK Tests"
        uses: ./.github/actions/tck-tests
        with:
          hyland-tck-pat: ${{ secrets.HYLAND_TCK_PAT }}
          maven-cli-opts: ${{ env.MAVEN_CLI_OPTS }}
