name: "Load Dependency Graph"
on:
  push:
    branches:
      - "master"
      - "release/**"
  schedule:
    - cron: "0 6 * * *" # Every day at 6:00 UTC
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scan-dependencies:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - name: Create Maven Wrapper properties
        run: |
          mkdir -p .mvn/wrapper
          echo "distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.9/apache-maven-3.9.9-bin.zip" > .mvn/wrapper/maven-wrapper.properties
          echo "wrapperUrl=https://repo.maven.apache.org/maven2/org/apache/maven/wrapper/maven-wrapper/3.3.2/maven-wrapper-3.3.2.jar" >> .mvn/wrapper/maven-wrapper.properties
      - uses: Alfresco/alfresco-build-tools/.github/actions/maven-dependency-scan@v18.15.0
        with:
          java-version: '21'
          maven-version: '3.9.9'
          maven-args: -Dscopes=compile,runtime
          maven-username: ${{ secrets.NEXUS_USERNAME }}
          maven-password: ${{ secrets.NEXUS_PASSWORD }}
          maven-settings-path: ".ci.settings.xml"
