name: Nightly Tests run

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every night at midnight

env:
  MAVEN_CLI_OPTS: "-B -e -fae -V -DinstallAtEnd=true -DfailIfNoTests=false -U -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Pdistribution "

jobs:
  nightly_tests:
    name: "Run nightly tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6
      - name: "Run TCK Tests"
        uses: ./.github/actions/tck-tests
        with:
          hyland-tck-pat: ${{ secrets.HYLAND_TCK_PAT }}
          maven-cli-opts: ${{ env.MAVEN_CLI_OPTS }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Notify on failure"
        if: failure()
        uses: Alfresco/alfresco-build-tools/.github/actions/send-teams-notification@v17.6.1
        with:
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          message: "Nightly tests failed"
