name: Veracode and Nightly Tests run

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every night at midnight

env:
  MAVEN_CLI_OPTS: "-B -e -fae -V -DinstallAtEnd=true -DfailIfNoTests=false -U -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Pdistribution "

jobs:
  veracode_sca:
    name: "Veracode - Source Clear Scan (SCA)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: Alfresco/alfresco-build-tools/.github/actions/free-hosted-runner-disk-space@v9.0.1
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v9.0.1
      - uses: Alfresco/alfresco-build-tools/.github/actions/veracode@v9.0.1
        env:
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        with:
          srcclr-api-token: ${{ secrets.SRCCLR_API_TOKEN }}
      - name: "Notify on failure"
        if: failure()
        uses: Alfresco/alfresco-build-tools/.github/actions/send-teams-notification@v9.0.1
        with:
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          message: "Veracode SCA scan failed"

  nightly_tests:
    name: "Run nightly tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v5
      - name: "Run TCK Tests"
        uses: ./.github/actions/tck-tests
        with:
          hyland-tck-pat: ${{ secrets.HYLAND_TCK_PAT }}
          maven-cli-opts: ${{ env.MAVEN_CLI_OPTS }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Notify on failure"
        if: failure()
        uses: Alfresco/alfresco-build-tools/.github/actions/send-teams-notification@v9.0.1
        with:
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          message: "Nightly tests failed"
