name: Veracode and Nightly Tests run

permissions:
  actions: read
  contents: read
  packages: read
  id-token: write

on:
  pull_request:
    branches:
      - feature/**
  push:
    branches:
      - feature/**
  schedule:
    - cron: "0 0 * * *"  # Runs every night at midnight

env:
  MAVEN_CLI_OPTS: "-B -e -fae -V -DinstallAtEnd=true -DfailIfNoTests=false -U -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Pdistribution "

jobs:
  veracode_sca:
    name: "Veracode - Source Clear Scan (SCA)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Alfresco/alfresco-build-tools/.github/actions/free-hosted-runner-disk-space@v8.14.1
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v8.14.1
      - uses: Alfresco/alfresco-build-tools/.github/actions/veracode@v8.14.1
        env:
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        with:
          srcclr-api-token: ${{ secrets.SRCCLR_API_TOKEN }}
      - name: "Notify on failure"
        if: failure()
        uses: Alfresco/alfresco-build-tools/.github/actions/send-teams-notification@v8.14.1
        with:
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          message: "Veracode SCA scan failed"

  nightly_tests:
    name: "Run nightly tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.HYLAND_TCK_PAT }}
      - uses: Alfresco/alfresco-build-tools/.github/actions/free-hosted-runner-disk-space@v8.14.1
      - name: "Clone TCK repository"
        shell: bash
        run: ./scripts/ci/cloneTCK.sh
        env:
          GITHUB_TOKEN: ${{ secrets.HYLAND_TCK_PAT }}
      - name: Docker Compose Up
        uses: HylandSoftware/ingestion-connector-tck-actions/docker-compose-up@main
        with:
          github-token: ${{ secrets.HYLAND_TCK_PAT }}
          working-directory: ${{ env.tck }}
      - name: "Set up JDK"
        uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v8.14.1
      - name: "Build application"
        shell: bash
        run: mvn ${{ inputs.maven-cli-opts }} clean install -DskipTests -pl live-ingester -am
      - name: "Run OpenApi Specification tests"
        shell: bash
        run: mvn test -Dtest=OpenApiTckRequestValidationTest -pl live-ingester
      - name: "Output TCK logs"
        if: success() || failure()
        shell: bash
        run: docker logs ingestion-connector-tck-api-1
      - name: Docker Compose Down
        uses: HylandSoftware/ingestion-connector-tck-actions/docker-compose-down@main
        with:
          working-directory: ${{ env.tck }}
#      - name: "Notify on failure"
#        if: failure()
#        uses: Alfresco/alfresco-build-tools/.github/actions/send-teams-notification@v8.14.1
#        with:
#          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
#          message: "Nightly tests failed"
